--
-- $Id:$
--

ALTER TABLE pay_options
CHANGE COLUMN option_key account_type_key int(11) AUTO_INCREMENT,
ADD COLUMN id varchar(32) NOT NULL DEFAULT '' AFTER account_type_key,
ADD COLUMN name varchar(64) NOT NULL DEFAULT '' AFTER id,
ADD COLUMN url varchar(64) NOT NULL DEFAULT '' AFTER name,
ADD COLUMN account_sharing_policy tinyint(1) NOT NULL DEFAULT 0 AFTER balance_check,
ADD COLUMN reseller_account_type tinyint(1) NOT NULL DEFAULT 0 AFTER balance_check,
DROP COLUMN implementation_type,
DROP COLUMN logo_url,
DROP COLUMN description_url,
DROP COLUMN payment_instructions,
DROP COLUMN implementation_id,
DROP COLUMN impl_param1,
DROP COLUMN impl_param2,
DROP COLUMN trust_level,
DROP COLUMN pay_destination_title,
DROP COLUMN pay_destination,
DROP COLUMN pay_limit,
DROP COLUMN transaction_cost_value,
DROP COLUMN transaction_cost_currency,
DROP COLUMN only_prereg_accounts,
DROP COLUMN expiry_date_field_type,
DROP COLUMN expiry_date_field_tag,
DROP COLUMN expiry_date_field_default,
DROP COLUMN account_nr_field_type,
DROP COLUMN account_nr_field_tag,
DROP COLUMN account_nr_field_default,
DROP COLUMN account_type_field_type,
DROP COLUMN account_type_field_tag,
DROP COLUMN account_type_field_default,
DROP COLUMN signature_field_type,
DROP COLUMN signature_field_tag,
DROP COLUMN signature_field_default,
DROP COLUMN authentic,
DROP COLUMN credit_options,
DROP COLUMN max_transaction_count,
DROP COLUMN min_payment_amount,
DROP COLUMN max_payment_amount,
DROP COLUMN max_payment_percentage,
DROP COLUMN payment_limit_period,
DROP COLUMN max_payment_period_amount,
DROP COLUMN max_payment_period_count,
DROP COLUMN account_registration_fee;
