ALTER TABLE `Refill`.`id_users_passwords_history`
    DROP FOREIGN KEY id_users_passwords_history_ibfk_1;

REPLACE INTO `Refill`.`resources` (`datakey`, `data`, `LastUpdated`, `ResourceGroup`, `startup`, `touched`, `last_modified`) VALUES
('?(Astd)/?(*)/?(OUTManageReseller)/edit_domain_users(EditDomainUsers)/group(CompleteGroup)/w(Window)/appearance(StringResource)','<div class="row pageHeader" id="resellerUser">
	<h4>§reseller_users§</h4>
</div> %|{select_user(SelectUser)/group(CompleteGroup)/w(Window)}|%
<br>%|{do_create_user(FlowControl)/group(CompleteGroup)/w(Window)}|%
	%|{do_remove_user(FlowControl)/group(CompleteGroup)/w(Window)}|%
	<br>%|{create_user(CreateNewUser)/group(CompleteGroup)/w(Window)}|%%|{edit_user_information(EditUserInformation)/group(CompleteGroup)/w(Window)}|%%|{edit_fields(EditUserFieldsRefillPartner)/group(CompleteGroup)/w(Window)}|%'
,'2011-06-08 15:35:02','?(RefillAdmin)','2011-06-08 15:43:31','2011-06-08 15:47:26','2011-06-08 15:47:26');

create index idx_parameter_value on reseller_extra_params (parameter_value);
alter table reseller_extra_params modify column receiver_key int(11);
create index idx_receiver_key on reseller_extra_params(receiver_key);
CREATE INDEX idx_import_key ON dwa_items (import_key);


REPLACE INTO `resources` (`datakey`, `data`, `LastUpdated`, `ResourceGroup`, `startup`, `touched`, `last_modified`) VALUES
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/group(CompleteGroup)/w(Window)/appearance(StringResource)','<div class="row" id="createNewUser"><div class="row pageHeader" id="createNewUserHeader"><h4>§create_new_user§</h4><p>This section allows the user to add a new reseller and enter his account information for use in the future.</p></div><div class="row"> %|{messages(OUMessageGroup)/group(CompleteGroup)/w(Window)}|%</div> %|{create_user(CreateNewUser)/role_description(HtmlMessage)/w(Window)}|% %|{create_user(CreateNewUser)/password_policy_description(HtmlMessage)/w(Window)}|%<div class="row" id="reqData"> <span>%|{(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/request_data(CompleteGroup)/w(Window)}|%</span></div></div>','2007-02-20 10:42:37','?(RefillAdmin)','2007-02-20 11:07:42','2007-02-20 11:09:43','2007-02-20 10:09:43'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/request_data(CompleteGroup)/w(Window)/appearance(StringResource)','<div class="row" id="createNewResellerUser"><div class="row" id="userDetails"><div class="columns four" id="userId"> <label for="" id="userLogin">§user_login§ <span class="helpQuestionMark" title="Enter the user Id">?</span> <font color="red">*</font> </label> <label id="userLogin" for="">%|{login(TextChoice)/w(Window)}|%</label></div><div class="columns four" id="email"> <label for="" id="emailLabel">§email§ <span class="helpQuestionMark" title="Enter the email address of the reseller">?</span> </label> <span>%|{email(TextChoice)/w(Window)}|%</span></div><div class="row columns four" id="userName"> <label for="" id="Username">§name§ <span class="helpQuestionMark" title="Enter the name of the reseller">?</span> </label> <span>%|{name(TextChoice)/w(Window)}|%</span></div></div><div class="row" id="section2"><div class="row columns four" id="password"> <label for="">%|{password(TextChoice)/w(Window)}|%</label></div><div class="row columns four" id="confirm_password"> <label for="">%|{confirm_password(TextChoice)/w(Window)}|%</label></div><div class="columns four" id="telephone"> <label for="" id="telephoneLabel">§telephone§ <span class="helpQuestionMark" title="Enter the contact no. of the reseller">?</span> </label> <span>%|{create_user(CreateNewUser)/telephone(TextChoice)/w(Window)}|%</span></div> </div><div class="row" id="section3"><div class="columns four" id="role"> <label>§role§ <span class="helpQuestionMark" title="Assign new role">?</span> <font color="red">*</font> </label> %|{roles(ElementChoiceOption)/group(CompleteGroup)/w(Window)}|%</div></div><div class="row" id="systemUserCustomerCommentsss"><div class="columns" id="customerComments"> <label for="" id="customerCommentsLabel">Customer Comments <span class="helpQuestionMark" title="Enter Comments">?</span> </label> <span id="customerCommentsField">%|{manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/customer_comments(TextChoice)/w(Window)}|%</span></div></div><div class="row" id="systemUserOtherDetails"><div class="columns" id="otherDetails"> <label for="" id="otherDetailsLabel">Other Details <span class="helpQuestionMark" title="Enter Other Details">?</span> </label> <span id="otherDetailsField">%|{manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/other_details(TextChoice)/w(Window)}|%</span></div><div class="row" id="subMitButton"> %|{submit(FlowControl)/group(CompleteGroup)/w(Window)}|%</div></div>','2007-02-02 11:31:47','?(RefillAdmin)','2007-02-05 08:51:35','2007-02-05 09:00:53','2007-02-05 08:00:53'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/customer_comments(TextChoice)/w(Window)/appearance(StringResource)','<TEXTAREA id=\"TextFieldNoWidth\" name=\"%|path|%\" ROWS=\"10\" COLS=\"100\">%|content|%</TEXTAREA>','2006-01-16 17:36:34','?(RefillAdmin)','2006-01-17 01:30:38','2006-01-17 08:47:17','2006-01-17 07:47:17'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/other_details(TextChoice)/w(Window)/appearance(StringResource)','<TEXTAREA id=\"TextFieldNoWidth\" name=\"%|path|%\" ROWS=\"10\" COLS=\"100\">%|content|%</TEXTAREA>','2006-01-16 17:36:34','?(RefillAdmin)','2006-01-17 01:30:38','2006-01-17 08:47:17','2006-01-17 07:47:17'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/messages(OUMessageGroup)/group(CompleteGroup)/w(Window)/langmap(StringResource)','header=Error when adding user','2006-10-13 16:29:56','?(RefillAdmin)','2006-11-03 12:42:46','2006-11-06 08:52:15','2006-11-06 07:52:15'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/password(TextChoice)/w(Window)/langmap(StringResource)','user_pwd=Password','2007-01-22 11:37:34','?(RefillAdmin)','2007-01-22 11:20:07','2007-01-22 11:37:34','2007-01-22 10:37:34'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/confirm_password(TextChoice)/w(Window)/langmap(StringResource)', 'confirm_pwd=Confirm Password', '2007-01-22 11:37:34', '?(RefillAdmin)', '2007-01-22 11:20:07', '2007-01-22 11:37:34', '2022-06-20 02:59:47'),
('?(Astd)/?(*)/?(EditDomainUsers)/edit_user_information(EditUserInformation)/please_enter_password(AtomicMessage)/w(Window)/langmap(StringResource)','msg=Please enter a password!','2001-11-05 10:56:11','?(RefillAdmin)','2005-07-05 19:05:27','2005-07-05 19:06:26','2005-07-05 17:06:26'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/customer_comments(TextChoice)/w(Window)/appearance(StringResource)','<TEXTAREA id=\"TextFieldNoWidth\" name=\"%|path|%\" ROWS=\"10\" COLS=\"100\">%|content|%</TEXTAREA>','2006-01-16 17:36:34','?(RefillAdmin)','2006-01-17 01:30:38','2006-01-17 08:47:17','2006-01-17 07:47:17'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/other_details(TextChoice)/w(Window)/appearance(StringResource)','<TEXTAREA id=\"TextFieldNoWidth\" name=\"%|path|%\" ROWS=\"10\" COLS=\"100\">%|content|%</TEXTAREA>','2006-01-16 17:36:34','?(RefillAdmin)','2006-01-17 01:30:38','2006-01-17 08:47:17','2006-01-17 07:47:17'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/messages(OUMessageGroup)/group(CompleteGroup)/w(Window)/langmap(StringResource)','header=Error when adding user','2006-10-13 16:29:56','?(RefillAdmin)','2006-11-03 12:42:46','2006-11-06 08:52:15','2006-11-06 07:52:15'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/password(TextChoice)/w(Window)/langmap(StringResource)','user_pwd=Password','2007-01-22 11:37:34','?(RefillAdmin)','2007-01-22 11:20:07','2007-01-22 11:37:34','2007-01-22 10:37:34'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/confirm_password(TextChoice)/w(Window)/langmap(StringResource)', 'confirm_pwd=Confirm Password', '2007-01-22 11:37:34', '?(RefillAdmin)', '2007-01-22 11:20:07', '2007-01-22 11:37:34', '2022-06-20 02:59:47'),
('?(Astd)/?(*)/?(OUTManageUsersAndAccessrights)/manage_domain_users(EditDomainUsers)/create_user(CreateNewUser)/please_enter_password(AtomicMessage)/w(Window)/langmap(StringResource)','msg=Please enter a password!','2001-11-05 10:56:11','?(RefillAdmin)','2005-07-05 19:05:27','2005-07-05 19:06:26','2005-07-05 17:06:26'),
('?(Astd)/?(*)/?(EditPartner)/edit_domain_users(EditDomainUsers)/create_user(CreateNewUser)/request_data(CompleteGroup)/w(Window)/appearance(StringResource)','<table id ="128">\r\n<tr><td colspan=3>\r\n<font color=\"red\">*</font>§instructions§\r\n</td></tr>\r\n<tr><td>\r\n<span class=\"input_header\">§user_login§</span><font color=\"red\">*</font><br>\r\n%|{login(TextChoice)/w(Window)}|%\r\n</td><td>\r\n<span class=\"input_header\">§user_pwd§</span><font color=\"red\">*</font><br>\r\n%|{password(TextChoice)/w(Window)}|%\r\n</td><td>\r\n<span class=\"input_header\">§name§</span><br>\r\n%|{name(TextChoice)/w(Window)}|%\r\n</td></tr>\r\n<tr><td>\r\n<span class=\"input_header\">§email§</span><br>\r\n%|{email(TextChoice)/w(Window)}|%\r\n</td><td>\r\n<span class=\"input_header\">§telephone§</span><br>\r\n%|{create_user(CreateNewUser)/telephone(TextChoice)/w(Window)}|%\r\n</td><td>\r\n<span class=\"input_header\">§role§</span><br>\r\n%|{roles(ElementChoiceOption)/group(CompleteGroup)/w(Window)}|%\r\n</td></tr>\r\n<tr><td colspan=\"3\">\r\n%|{submit(FlowControl)/group(CompleteGroup)/w(Window)}|%\r\n</td></tr>\r\n</table>\r\n\r\n\r\n\r\n\r\n\r\n','2006-12-14 18:14:20','?(RefillAdmin)','2006-12-14 20:04:27','2006-12-15 00:51:27','2006-12-14 23:51:27');

REPLACE INTO `resources` (`datakey`, `data`, `LastUpdated`, `ResourceGroup`, `startup`, `touched`, `last_modified`) VALUES
('?(Astd)/?(*)/?(OUTSearchAuditLog)/search_group(CompleteGroup)/w(Window)/appearance(StringResource)','<div class="searchAuditLog container pageHeader"><h4>§search_audit_log§</h4><p>This section is used to log the admin actions</p><div class="auditLogFiltersSearchDiv"><div class="auditLogFiltersSectionOne row"><div class="fromDateTimeDiv columns four"> <label for="" id="fromDateTimeLabel">§from_datetime§ <span class="helpQuestionMark" title="Select date">?</span> </label> %|{search_audit_log(OUTSearchAuditLog)/from_datetime(OUTChooseDateTime)/w(Window)}|%</div><div class="toDateTimeDiv columns four"> <label for="" id="toDateTimeLabel">§to_datetime§ <span class="helpQuestionMark" title="Select Date">?</span> </label> %|{search_audit_log(OUTSearchAuditLog)/to_datetime(OUTChooseDateTime)/w(Window)}|%</div><div class="mimeTypeDiv columns four"> <label for="" id="mimeTypeLabel">§mimetype§ <span class="helpQuestionMark" title="Select type">?</span> </label> %|{mimetype_choice(ElementChoiceOption)/group(CompleteGroup)/w(Window)}|%</div></div><div class="auditLogFiltersSectionTwo row"><div class="actionDiv columns four"> <label for="" id="actionLabel">§action§ <span class="helpQuestionMark" title="Select action">?</span> </label> %|{action_choice(ElementChoiceOption)/group(CompleteGroup)/w(Window)}|%</div><div class="userIdDiv columns four"> <label for="" id="userIdLabel">§user_id§ <span class="helpQuestionMark" title="Enter user id">?</span> </label> %|{search_audit_log(OUTSearchAuditLog)/user_id(OUTChooseText)/w(Window)}|%</div><div class="descriptionDiv columns four"> <label for="" id="userIdLabel">§description§ <span class="helpQuestionMark" title="Enter description">?</span> </label> %|{search_audit_log(OUTSearchAuditLog)/description(OUTChooseText)/w(Window)}|%</div></div></div><div class="flowControlForAuditSearch row"><div class="flowControlButtons"> %|{do_search(FlowControl)/group(CompleteGroup)/w(Window)}|% %|{export_data(DODRawData)/group(CompleteGroup)/w(Window)}|%</div></div></div>','2008-08-19 14:15:54','?(RefillAdmin)','2008-08-19 15:40:04','2008-08-19 15:41:26','2008-08-19 15:41:26'),
('?(Len)/?(*)/?(OUTSearchAuditLog)/search_group(CompleteGroup)/w(Window)/langmap(StringResource)','search_audit_log=Search audit log\r\nfrom_datetime=From\r\nto_datetime=To\r\naction=Action\r\nuser_id=User id\r\ndescription=Description\r\nmimetype=Mime Type','2008-08-19 14:14:17','?(RefillAdmin)','2008-08-19 13:59:36','2008-08-19 14:14:17','2008-08-19 14:14:17');

REPLACE INTO `id_audit_actions` (`action_key`, `action`, `description`) VALUES
(1000,'ADD GROUP',''),
(1001,'ADD GROUPS',''),
(1002,'DELETE GROUP',''),
(1003,'ADD GROUP MEMBERS',''),
(1004,'REMOVE GROUP MEMBERS',''),
(1005,'UPDATE GROUP','');