---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-gp-grn-processor-main
  namespace: {{ .Release.Namespace }}
data:
{{ tpl (.Files.Glob "configs/gp-grn-processor/*").AsConfig . | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-gp-grn-processor-templates
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/gp-grn-processor/templates/notification/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-gp-grn-processor-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-gp-grn-processor" | quote }}
