---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-gp-idm-voucher-activator-main
  namespace: {{ .Release.Namespace }}
{{- $context := . }}
{{- $files := .Files }}
{{- $binaryExts := list ".ttf" ".jpeg" ".pkcs12" ".pem" ".crt" ".key" ".jks" ".p12" }}
{{- $pathGlob := "configs/gp-idm-voucher-activator/*" }}
binaryData:
{{- range $path, $ := $files.Glob $pathGlob }}
  {{- $ext := ext $path }}
  {{- if has $ext $binaryExts }}
  {{ base $path }}: {{ $files.Get $path | b64enc }}
  {{- end }}
{{- end }}
data:
{{- range $path, $file := $files.Glob $pathGlob }}
  {{- $filename := base $path }}
  {{- $ext := ext $path }}
  {{- if not (has $ext $binaryExts) }}
    {{- if eq $ext ".json" }}
  {{ $filename }}: |
{{ $file | indent 4 }}
    {{- else }}
  {{ $filename }}: |-
{{ tpl ($file | toString) $context | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-gp-idm-voucher-activator-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-gp-idm-voucher-activator" | quote }}
