---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-main
  namespace: {{ .Release.Namespace }}
{{- $context := . }}
{{- $files := .Files }}
{{- $binaryExts := list ".ttf" ".jpeg" ".pkcs12" ".pem" ".crt" ".key" ".jks" ".p12" ".jar" }}
{{- $pathGlob := "configs/kyc/*" }}

{{- $binaryFiles := dict }}
{{- range $path, $_ := $files.Glob $pathGlob }}
  {{- $ext := ext $path }}
  {{- if has $ext $binaryExts }}
    {{- $_ := set $binaryFiles $path true }}
  {{- end }}
{{- end }}

{{- if gt (len $binaryFiles) 0 }}
binaryData:
{{- range $path, $_ := $files.Glob $pathGlob }}
  {{- $ext := ext $path }}
  {{- if has $ext $binaryExts }}
  {{ base $path }}: {{ $files.GetBytes $path | toString | b64enc }}
  {{- end }}
{{- end }}
{{- end }}

data:
{{- range $path, $_ := $files.Glob $pathGlob }}
  {{- $filename := base $path }}
  {{- $ext := ext $path }}
  {{- if not (has $ext $binaryExts) }}
    {{- $content := $files.Get $path | toString }}
    {{- if eq $ext ".json" }}
  {{ $filename }}: |
{{ $content | indent 4 }}
    {{- else }}
  {{ $filename }}: |-
{{ tpl $content $context | indent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-templates-audit
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/kyc/templates/audit/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-templates-tdr
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/kyc/templates/tdr/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-actions
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/kyc/actions_groovy/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-mappings
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/kyc/mappings/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-notification
  namespace: {{ .Release.Namespace }}
data:
{{ (.Files.Glob "configs/kyc/notification/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-kyc-copy
  namespace: {{ .Release.Namespace }}
data:
  configs-copy: {{ .Files.Get "scripts/configs-copy-kyc" | quote }}
