apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app-url-{{ .Release.Namespace }}
  namespace: {{ .Values.ingress_namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.app_url_domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-nginx
            port:
              number: 18080
