---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-dealer-management-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.dealermanagement }}
  storageClassName: {{ .Values.storageclass_name }}
