---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-idm-asset-management-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.idmassetmanagement }}
  storageClassName: {{ .Values.storageclass_name }}
