---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-ims-bridge-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.imsbridge }}
  storageClassName: {{ .Values.storageclass_name }}
