---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-nginx-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.nginx }}
  storageClassName: {{ .Values.storageclass_name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.nginx }}
  storageClassName: {{ .Values.storageclass_name }}
