#!/bin/bash

mkdir -p /opt/seamless/conf/coreproxy

cp -L /main/* /opt/seamless/conf/
cp -L /coreproxy/* /opt/seamless/conf/coreproxy/



# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/coreproxy+/var/seamless/log/coreproxy/coreproxy/${REPLICA_NAME}+g" /opt/seamless/conf/coreproxy/log4j2.xml
