#!/bin/bash

mkdir -p /opt/seamless/conf/region-management-core
mkdir /opt/seamless/conf/region-management-core/templates

cp -L /main/* /opt/seamless/conf/
cp -L /region-management-main/* /opt/seamless/conf/region-management-core/
cp -L /region-management-templates/* /opt/seamless/conf/region-management-core/templates/

# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/region-management-core+/var/seamless/log/region-management-core/region-management-core/${REPLICA_NAME}+g" /opt/seamless/conf/region-management-core/log4j2.properties
