#!/bin/bash

mkdir -p /opt/seamless/conf/template-management-system

cp -L /main/* /opt/seamless/conf/
cp -L /template-management-main/* /opt/seamless/conf/template-management-system/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/template-management-system+/var/seamless/log/template-management-system/template-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/template-management-system/log4j2.xml
