#!/bin/bash

mkdir -p /opt/seamless/conf/bi-tdr-exporter

cp -L /main/* /opt/seamless/conf/
cp -L /bi-tdr-exporter-main/* /opt/seamless/conf/bi-tdr-exporter/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/bi-tdr-exporter+/var/seamless/log/bi-tdr-exporter/bi-tdr-exporter/${REPLICA_NAME}+g" /opt/seamless/conf/bi-tdr-exporter/log4j2.xml
