#!/bin/bash

mkdir -p /opt/seamless/conf/group-management/templates/{audit,notification,tdr}

cp -L /main/* /opt/seamless/conf/
cp -L /group-management-main/* /opt/seamless/conf/group-management/
cp -L /group-management-audit/* /opt/seamless/conf/group-management/templates/audit/
cp -L /group-management-notification/* /opt/seamless/conf/group-management/templates/notification/
cp -L /group-management-tdr/* /opt/seamless/conf/group-management/templates/tdr/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/group-management+/var/seamless/log/group-management/group-management/${REPLICA_NAME}+g" /opt/seamless/conf/group-management/log4j2.xml
