#!/bin/bash

mkdir -p /opt/seamless/conf/gp-idm-bprs-link

cp -L /main/* /opt/seamless/conf/
cp -L /idm-bprs-link-main/* /opt/seamless/conf/gp-idm-bprs-link/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/gp-idm-bprs-link+/var/seamless/log/gp-idm-bprs-link/gp-idm-bprs-link/${REPLICA_NAME}+g" /opt/seamless/conf/gp-idm-bprs-link/log4j.properties
sed -i "s+/var/seamless/log/gp-idm-bprs-link+/var/seamless/log/gp-idm-bprs-link/gp-idm-bprs-link/${REPLICA_NAME}+g" /opt/seamless/conf/gp-idm-bprs-link/log4j2.xml
