#!/bin/bash

mkdir -p /opt/seamless/conf/dealer-management-system/templates/dataFeed

cp -L /main/* /opt/seamless/conf/
cp -L /dealer-management-main/* /opt/seamless/conf/dealer-management-system/
cp -L /dealer-management-templates/* /opt/seamless/conf/dealer-management-system/templates/dataFeed/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/dealer-management-system+/var/seamless/log/dealer-management-system/dealer-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/dealer-management-system/log4j2.xml
sed -i "s+/var/seamless/log/dealer-management-system+/var/seamless/log/dealer-management-system/dealer-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/dealer-management-system/dealer-management-system.properties
