#!/bin/bash

mkdir -p /opt/seamless/conf/access-management-system/templates
mkdir -p /opt/seamless/conf/access-management-system/auditFeed/templates

cp -L /main/* /opt/seamless/conf/
cp -L /access-management-main/* /opt/seamless/conf/access-management-system/
cp -L /access-management-templates/* /opt/seamless/conf/access-management-system/templates/
cp -L /access-management-audit-templates/* /opt/seamless/conf/access-management-system/auditFeed/templates/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/access-management-system+/var/seamless/log/access-management-system/access-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/access-management-system/log4j2.xml
