#!/bin/bash

mkdir -p /opt/seamless/conf/ldaplink-core/scripts

cp -L /main/* /opt/seamless/conf/
cp -L /ldaplink-main/* /opt/seamless/conf/ldaplink-core/
cp -L /ldaplink-scripts/* /opt/seamless/conf/ldaplink-core/scripts/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/ldaplink-core+/var/seamless/log/ldaplink-core/ldaplink-core/${REPLICA_NAME}+g" /opt/seamless/conf/ldaplink-core/log4j2.xml
