#!/bin/bash

mkdir -p /opt/seamless/conf/contract-management-system

cp -L /main/* /opt/seamless/conf/
cp -L /contract-management/* /opt/seamless/conf/contract-management-system/



# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/contract-management+/var/seamless/log/contract-management/contract-management/${REPLICA_NAME}+g" /opt/seamless/conf/contract-management-system/log4j2.xml
