#!/bin/bash

mkdir -p /opt/seamless/conf/otp-management-system/

cp -L /main/* /opt/seamless/conf/
cp -L /otp-management/* /opt/seamless/conf/otp-management-system/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/otp-management-system+/var/seamless/log/otp-management-system/otp-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/otp-management-system/log4j2.properties
