#!/bin/bash

mkdir -p /opt/seamless/conf/inventory-management-system/{scripts,templates}
mkdir -p /opt/seamless/conf/inventory-management-system/templates/{audit,tdr,notification}

cp -L /main/* /opt/seamless/conf/
cp -L /inventory-management-main/* /opt/seamless/conf/inventory-management-system/
cp -L /inventory-management-scripts/* /opt/seamless/conf/inventory-management-system/scripts/
cp -L /inventory-management-audit/* /opt/seamless/conf/inventory-management-system/templates/audit/
cp -L /inventory-management-tdr/* /opt/seamless/conf/inventory-management-system/templates/tdr/
cp -L /inventory-management-notification/* /opt/seamless/conf/inventory-management-system/templates/notification/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/inventory-management-system+/var/seamless/log/inventory-management-system/inventory-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/inventory-management-system/log4j2.properties
