#!/bin/bash

mkdir -p /opt/seamless/conf/order-management-system/templates/{audit,notification,tdr,invoice}

cp -L /main/* /opt/seamless/conf/
cp -L /order-management-main/* /opt/seamless/conf/order-management-system/
cp -L /order-management-audit/* /opt/seamless/conf/order-management-system/templates/audit/
cp -L /order-management-notification/* /opt/seamless/conf/order-management-system/templates/notification/
cp -L /order-management-notification/* /opt/seamless/conf/order-management-system/templates/notification/
cp -L /order-management-tdr/* /opt/seamless/conf/order-management-system/templates/tdr/
cp -L /order-management-invoice/* /opt/seamless/conf/order-management-system/templates/invoice/

# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/order-management-system+/var/seamless/log/order-management-system/order-management-system/${REPLICA_NAME}+g" /opt/seamless/conf/order-management-system/log4j2.properties
