#!/bin/bash

mkdir -p /opt/seamless/conf/account-management-service/templates
mkdir -p /opt/seamless/conf/account-management-service/auditFeed/templates

cp -L /main/* /opt/seamless/conf/
cp -L /account-management-main/* /opt/seamless/conf/account-management-service/
cp -L /account-management-templates/* /opt/seamless/conf/account-management-service/templates/
cp -L /account-management-audit-templates/* /opt/seamless/conf/account-management-service/auditFeed/templates/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/account-management-service+/var/seamless/log/account-management-service/account-management-service/${REPLICA_NAME}+g" /opt/seamless/conf/account-management-service/log4j2.properties
