#!/bin/bash

mkdir -p /opt/seamless/conf/reference-generator

cp -L /main/* /opt/seamless/conf/
cp -L /reference-generator/* /opt/seamless/conf/reference-generator/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/reference-generator+/var/seamless/log/reference-generator/reference-generator/${REPLICA_NAME}+g" /opt/seamless/conf/reference-generator/log4j2.properties
