#!/bin/bash

mkdir -p /opt/seamless/conf/gp-idm-asset-management

cp -L /main/* /opt/seamless/conf/
cp -L /idm-asset-management-main/* /opt/seamless/conf/gp-idm-asset-management/


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
REPLICA_NAME=`echo $HOSTNAME | sed -E 's/.*-//'`
sed -i "s+/var/seamless/log/gp-idm-asset-management+/var/seamless/log/gp-idm-asset-management/gp-idm-asset-management/${REPLICA_NAME}+g" /opt/seamless/conf/gp-idm-asset-management/log4j.properties
