#!/bin/bash

mkdir -p /opt/seamless/conf/identity-management/templates

cp -L /main/* /opt/seamless/conf/
cp -L /identity-management-main/* /opt/seamless/conf/identity-management/
cp -L /identity-management-templates/* /opt/seamless/conf/identity-management/templates/

value=`echo ${HOSTNAME} | awk -F'-' '{$NF += 1; printf "%02d\n", $NF}'`
sed -i "s+node_id=01+node_id=${value}+g" /opt/seamless/conf/identity-management/identity-management.properties
sed -i "s+node_id=01+node_id=${value}+g" /opt/seamless/conf/system.properties

sed -i "s+reference_generator.node_id=01+reference_generator.node_id=${value}+g" /opt/seamless/conf/identity-management/identity-management.properties


# SEGREGATE REPLICA LOGS INTO SEPARATE DIRS
sed -i "s+/var/seamless/log/identity-management+/var/seamless/log/identity-management/identity-management/${HOSTNAME}+g" /opt/seamless/conf/identity-management/log4j2.xml
