---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: access-management
  name: svc-access-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8374
    targetPort: 8374
  selector:
    app: access-management
  type: ClusterIP
