---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: accountlink
  name: svc-accountlink
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8091
    targetPort: 8091
  selector:
    app: accountlink
  type: ClusterIP
