---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account-management
  name: svc-account-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8092
    targetPort: 8092
  selector:
    app: account-management
  type: ClusterIP
