---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: batch-scheduling
  name: svc-batch-scheduling
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8085
    targetPort: 8085
    nodePort: 32085
  selector:
    app: batch-scheduling
  type: NodePort

