---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: contract-management
  name: svc-contract-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: cm1
    port: 38082
    targetPort: 38082
  - name: cm2
    port: 35729
    targetPort: 35729
  selector:
    app: contract-management
  type: ClusterIP
