---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: idm-ers-link
  name: svc-idm-ers-link
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 15500
    targetPort: 15500
  selector:
    app: idm-ers-link
  type: ClusterIP
