---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-management
  name: svc-identity-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8219
    targetPort: 8219
  selector:
    app: identity-management
  type: ClusterIP
