---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-management
  name: svc-inventory-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 10103
    targetPort: 10103
  selector:
    app: inventory-management
  type: ClusterIP
