---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyc
  name: svc-kyc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8297
    targetPort: 8297
  selector:
    app: kyc
  type: ClusterIP
