---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: link-simulator
  name: svc-link-simulator
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8096
      targetPort: 8096
    - name: https
      port: 8095
      targetPort: 8095
  selector:
    app: link-simulator
  type: ClusterIP
