---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: svc-nginx
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 18080
    {{- if eq .Release.Namespace "ers-dev" }}
    nodePort: 30070
    {{- else if eq .Release.Namespace "ers-staging" }}
    nodePort: 31070
    {{- else if eq .Release.Namespace "ers" }}
    nodePort: 32070
    {{- end }}
    targetPort: 18080
  selector:
    app: nginx
  type: NodePort
