---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-manager
  name: svc-notification-manager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8277
    targetPort: 8277
  selector:
    app: notification-manager
  type: ClusterIP
