---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: object-store
  name: svc-object-store
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: object-store
  type: ClusterIP
