---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-management
  name: svc-order-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9595
    targetPort: 9595
  selector:
    app: order-management
  type: ClusterIP
