---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: region-management
  name: svc-region-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: region-management
  type: ClusterIP
