---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: template-management
  name: svc-template-management
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 8378
    targetPort: 8378
  selector:
    app: template-management
  type: ClusterIP
