apiVersion: v1
kind: ConfigMap
metadata:
  name: my-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to My Site!</title>
      <h2>Ali Mehdi Here! Tell me how i can assist you</h2>
    </head>
    <body>
      <h1>Hello from ConfigMap!</h1>
    </body>
    </html>
