apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web23
spec:
  initContainers:
    - name: copy-config
      image: busybox
      command: ["sh", "-c", "cp /config/index.html /html/index.html"]
      volumeMounts:
        - name: vol-cm-main
          mountPath: /config
        - name: vol-cm-html
          mountPath: /html    
  containers:
    - name: nginx-web
      image: nginx:alpine
      volumeMounts:
        - name: vol-cm-html
          mountPath: /usr/share/nginx/html/
        - name: vol-nginx-log
          mountPath: /var/log/nginx/
  volumes:
    - name: vol-cm-main
      configMap:
        name: index-new-html
    - name: vol-cm-html
      emptyDir: {}
    - name: vol-nginx-log
      persistentVolumeClaim:
          claimName: nginx-pvc

