---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: batch-scheduling
  namespace: {{ .Release.Namespace }}
  labels:
    app: batch-scheduling
    egressTraffic: green
    version: v1
spec:
  replicas: {{ index .Values.replica.batchscheduling .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: batch-scheduling
      version: v1
  template:
    metadata:
      labels:
        app: batch-scheduling
        version: v1
    spec:
      initContainers:
      - name: copy-configs
        image: {{ .Values.image.init_centos }}
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-batch-scheduling-main
          mountPath: /batch-scheduling-main
        - name: vol-cm-batch-scheduling-templates
          mountPath: /batch-scheduling-templates
        - name: vol-cm-batch-scheduling-samples
          mountPath: /batch-scheduling-samples
        - name: vol-cm-batch-scheduling-feeder
          mountPath: /batch-scheduling-feeder
        - name: vol-cm-batch-scheduling-audit-feeder
          mountPath: /batch-scheduling-audit-feeder
        - name: vol-cm-batch-scheduling-notifications
          mountPath: /batch-scheduling-notifications
        - name: vol-cm-batch-scheduling-copy
          mountPath: /scripts
      containers:
      - name: batch-scheduling
        image: {{ .Values.image.batchscheduling }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        readinessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8085"
          {{- include "probe" (list . "readiness" "batchscheduling") | nindent 10 }}
        livenessProbe:
          exec:
            command:
            - telnet
            - 127.0.0.1
            - "8085"
          {{- include "probe" (list . "liveness" "batchscheduling") | nindent 10 }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /usr/share/zoneinfo/Asia/Dhaka
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-batch-scheduling
          mountPath: {{ .Values.logs }}/batch-scheduling
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-batch-scheduling-main
        configMap:
          name: cm-batch-scheduling-main
      - name: vol-cm-batch-scheduling-templates
        configMap:
          name: cm-batch-scheduling-templates
      - name: vol-cm-batch-scheduling-feeder
        configMap:
          name: cm-batch-scheduling-feeder
      - name: vol-cm-batch-scheduling-audit-feeder
        configMap:
          name: cm-batch-scheduling-audit-feeder
      - name: vol-cm-batch-scheduling-samples
        configMap:
          name: cm-batch-scheduling-samples
      - name: vol-cm-batch-scheduling-notifications
        configMap:
          name: cm-batch-scheduling-notifications
      - name: vol-logs-batch-scheduling
        persistentVolumeClaim:
          claimName: logs-batch-scheduling-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-batch-scheduling-copy
        configMap:
          name: cm-batch-scheduling-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
