---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coreproxy
  namespace: {{ .Release.Namespace }}
  labels:
    app: coreproxy
    egressTraffic: green
spec:
  replicas: {{ index .Values.replica.coreproxy .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: coreproxy
  template:
    metadata:
      labels:
        app: coreproxy
    spec:
      initContainers:
      - name: copy-configs
        image: {{ .Values.image.init_centos }}
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-coreproxy-main
          mountPath: /coreproxy
        - name: vol-cm-coreproxy-copy
          mountPath: /scripts
      containers:
      - name: coreproxy
        image: {{ .Values.image.coreproxy }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8912
        - containerPort: 8983
        readinessProbe:
          tcpSocket:
            port: 8912
          {{- include "probe" (list . "readiness" "coreproxy") | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 8912
          {{- include "probe" (list . "liveness" "coreproxy") | nindent 10 }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /usr/share/zoneinfo/Asia/Dhaka
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-coreproxy
          mountPath: {{ .Values.logs }}/coreproxy
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-coreproxy-main
        configMap:
          name: cm-coreproxy-main
      - name: vol-logs-coreproxy
        persistentVolumeClaim:
          claimName: logs-coreproxy-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-coreproxy-copy
        configMap:
          name: cm-coreproxy-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
