---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app: notification-manager
    egressTraffic: green
spec:
  replicas: {{ index .Values.replica.notificationmanager .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: notification-manager
  template:
    metadata:
      labels:
        app: notification-manager
    spec:
      initContainers:
      - name: copy-configs
        image: {{ .Values.image.init_centos }}
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-notification-manager-main
          mountPath: /notification-manager-main
        - name: vol-cm-notification-manager-feeder
          mountPath: /notification-manager-feeder
        - name: vol-cm-notification-manager-keys
          mountPath: /notification-manager-keys
        - name: vol-cm-notification-manager-copy
          mountPath: /scripts
      containers:
      - name: notification-manager
        image: {{ .Values.image.notificationmanager }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8277
        readinessProbe:
          tcpSocket:
            port: 8277
          {{- include "probe" (list . "readiness" "notificationmanager") | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 8277
          {{- include "probe" (list . "liveness" "notificationmanager") | nindent 10 }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /usr/share/zoneinfo/Asia/Dhaka
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - mountPath: {{ .Values.logs }}/notification-manager
          name: vol-logs-notification-manager
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-notification-manager-main
        configMap:
          name: cm-notification-manager-main
      - name: vol-cm-notification-manager-feeder
        configMap:
          name: cm-notification-manager-feeder
      - name: vol-cm-notification-manager-keys
        configMap:
          name: cm-notification-manager-keys
      - name: vol-logs-notification-manager
        persistentVolumeClaim:
          claimName: logs-notification-manager-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-notification-manager-copy
        configMap:
          name: cm-notification-manager-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
