---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store
  namespace: {{ .Release.Namespace }}
  labels:
    app: object-store
    egressTraffic: green
spec:
  replicas: {{ index .Values.replica.objectstore .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: object-store
  template:
    metadata:
      labels:
        app: object-store
    spec:
      initContainers:
      - name: copy-configs
        image: {{ .Values.image.init_centos }}
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-object-store-main
          mountPath: /object-store-main
        - name: vol-cm-object-store-locales
          mountPath: /object-store-locales
        - name: vol-cm-object-store-copy
          mountPath: /scripts
      containers:
      - name: object-store
        image: {{ .Values.image.objectstore }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        readinessProbe:
          tcpSocket:
            port: 3000
          {{- include "probe" (list . "readiness" "objectstore") | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 3000
          {{- include "probe" (list . "liveness" "objectstore") | nindent 10 }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /usr/share/zoneinfo/Asia/Dhaka
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-logs-object-store
          mountPath: {{ .Values.logs }}/object-store-manager
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-object-store-main
        configMap:
          name: cm-object-store-main
      - name: vol-cm-object-store-locales
        configMap:
          name: cm-object-store-locales
      - name: vol-logs-object-store
        persistentVolumeClaim:
          claimName: logs-object-store-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-object-store-copy
        configMap:
          name: cm-object-store-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
