---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-management
  namespace: {{ .Release.Namespace }}
  labels:
    app: template-management
    egressTraffic: green
spec:
  replicas: {{ index .Values.replica.templatemanagement .Values.env }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge:  40%
       maxUnavailable: 20%
  selector:
    matchLabels:
      app: template-management
  template:
    metadata:
      labels:
        app: template-management
    spec:
      initContainers:
      - name: copy-configs
        image: {{ .Values.image.init_centos }}
        imagePullPolicy: IfNotPresent
        command: ['bash','/scripts/configs-copy']
        volumeMounts:
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - name: vol-cm-main
          mountPath: /main
        - name: vol-cm-template-management-main
          mountPath: /template-management-main
        - name: vol-cm-template-management-copy
          mountPath: /scripts
      containers:
      - name: template-management
        image: {{ .Values.image.templatemanagement }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8378
        readinessProbe:
          tcpSocket:
            port: 8378
          {{- include "probe" (list . "readiness" "templatemanagement") | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: 8378
          {{- include "probe" (list . "liveness" "templatemanagement") | nindent 10 }}
        env:
        - name: DEFAULT_TIME_ZONE
          value: "{{ .Values.timezone }}"
        - name: TZ
          value: "{{ .Values.timezone }}"
        volumeMounts:
        - name: tz-{{ .Values.country }}
          mountPath: /etc/localtime
        - name: config-dir-main
          mountPath: {{ .Values.conf }}
        - mountPath: {{ .Values.logs }}/template-management-system
          name: vol-logs-template-management
      volumes:
      - name: tz-{{ .Values.country }}
        hostPath:
          path: /usr/share/zoneinfo/{{ .Values.timezone }}
      - name: vol-cm-main
        configMap:
          name: cm-main
      - name: vol-cm-template-management-main
        configMap:
          name: cm-template-management-main
      - name: vol-logs-template-management
        persistentVolumeClaim:
          claimName: logs-template-management-{{ .Release.Namespace }}
      - name: config-dir-main
        emptyDir: {}
      - name: vol-cm-template-management-copy
        configMap:
          name: cm-template-management-copy
      imagePullSecrets:
      - name: {{ .Values.secret }}
