---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-alertmanager-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storageCapacity.alertmanager }}
{{- if eq .Values.storage_type "manual" }}
  selector:
    matchLabels:
      type: local
      name: logs-alertmanager-{{ .Release.Namespace }}
{{- end }}
  storageClassName: {{ .Values.storageclass_name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
{{- if eq .Values.private_registry true }}
      imagePullSecrets:
      - name: {{ .Values.secret }}
{{- end }}
      containers:
      - name: alertmanager
        image: {{ .Values.prometheus_container_rgistry_url }}/{{ .Values.image.alertmanager }}
        imagePullPolicy: IfNotPresent
        args:
        - "--config.file=/etc/alertmanager/config.yml"
        - "--storage.path=/var/seamless/log/alertmanager"
        ports:
        - containerPort: 9093
        resources:
          {{- include "resources.alertmanager" . | nindent 10 }}
        volumeMounts:
        - name: vol-cm-alertmanager-main
          mountPath: /etc/alertmanager
        - name: vol-cm-alertmanager-templates
          mountPath: /etc/alertmanager-templates
        - name: vol-logs-alertmanager-{{ .Release.Namespace }}
          mountPath: /var/seamless/log/alertmanager
      volumes:
      - name: vol-cm-alertmanager-main
        configMap:
          name: cm-alertmanager-main
      - name: vol-cm-alertmanager-templates
        configMap:
          name: cm-alertmanager-templates
      - name: vol-logs-alertmanager-{{ .Release.Namespace }}
        persistentVolumeClaim:
            claimName: logs-alertmanager-{{ .Release.Namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-alertmanager
  namespace: {{ .Release.Namespace }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9093'
spec:
  selector:
    app: alertmanager
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000
