---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: svc-minio
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 31900
  selector:
    app: minio
  type: NodePort
