---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: svc-rabbitmq
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: rabbitmq
    port: 15672
    targetPort: 15672
  - name: rabbitmq2
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
